# Auto-generated by /home/cc/Code/linaro-edk2-2015.07/BaseTools/BuildEnv
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/home/cc/Code/linaro-edk2-2015.07
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/home/cc/Code/linaro-edk2-2015.07/BaseTools
fi
if [ -e /home/cc/Code/linaro-edk2-2015.07/BaseTools/Bin/Linux-x86_64 ]
then
  if [ ${PATH//home/cc/Code/linaro-edk2-2015.07/BaseTools/Bin/Linux-x86_64/} == $PATH ]
  then
    export PATH=/home/cc/Code/linaro-edk2-2015.07/BaseTools/Bin/Linux-x86_64:$PATH
  fi
fi
